### ISSUE TITLE
Create server on Heroku

### ISSUE THREAD

**Issue by arun-esh** [ritikajaidka/nys#4]
- [x] Create account on Heroku.
- [x] Create an app on Heroku.
- [x] Associate your GitHub account with Heroku.
- [x] Make sure main branch is configured for source code

#  🛟 Please get in touch if you encounter any issues 🛟

**Comment by ritikajaidka** [comment]
Created an account and set up an app on it. Associated GitHub account with Heroku. However, getting below error while trying to deploy main branch.  @arun-esh 

![Capture](https://user-images.githubusercontent.com/43687921/188509764-3d122f02-e473-4a8e-9a5a-e6ebb8b27113.PNG)

**Comment by arun-esh** [comment]
Great work! Error because my recent PR is still under review.

**Comment by arun-esh** [comment]
Issue is resolved! We are live on Heroku.
