### ISSUE TITLE
Configure Heroku CI 

### ISSUE THREAD

**Issue by arun-esh** [ritikajaidka/nys#5]
- [x] Heroku CI 
- [x] Test the functionality @ritikajaidka 

## Please work with @ritikajaidka to get access to Heroku account.

**Comment by jalpa015** [comment]
@arun-esh @ritikajaidka I have added the CI file on the assigned branch to this issue. PR #9 is the related PR. 

@ritikajaidka needs to setup the secret key. Also check @ritikajaidka 's email and APP name in YAML file.

**Comment by arun-esh** [comment]
> @arun-esh @ritikajaidka I have added the CI file on the assigned branch to this issue. PR #9 is the related PR. 
> 
> 
> 
> @ritikajaidka needs to setup the secret key. Also check @ritikajaidka 's email and APP name in YAML file. 

Only Heroku account holder can generate API secret?

**Comment by jalpa015** [comment]
> > @arun-esh @ritikajaidka I have added the CI file on the assigned branch to this issue. PR #9 is the related PR.
> > @ritikajaidka needs to setup the secret key. Also check @ritikajaidka 's email and APP name in YAML file.
> 
> Only Heroku account holder can generate API secret?

Anyone can with access I guess. Email should match the account of API secret key.

**Comment by arun-esh** [comment]
Make sense! @ritikajaidka please let me know if you need any assistance.

**Comment by jalpa015** [comment]
I can share the steps here - 

On Heroku click on your profile image in the upper right and choose Account Settings. Scroll down to the API Key section. Click Reveal and then copy the key.

In GitHub, click Settings for the nys repo. Click Secrets. Click New repository secret. In the Name field, type: HEROKU_API_KEY. In the Value field, paste the Heroku API Key that you copied. Click Add secret.

**Comment by arun-esh** [comment]
> I can share the steps here -
> 
> On Heroku click on your profile image in the upper right and choose Account Settings. Scroll down to the API Key section. Click Reveal and then copy the key.
> 
> In GitHub, click Settings for the nys repo. Click Secrets. Click New repository secret. In the Name field, type: HEROKU_API_KEY. In the Value field, paste the Heroku API Key that you copied. Click Add secret.

Let's document in the documentation folder as well.

**Comment by arun-esh** [comment]
> Make sense! @ritikajaidka please let me know if you need any assistance.

I think it is better to connect with @jalpa015 so that she can raise PR as well along with the information she need from you @ritikajaidka

**Comment by arun-esh** [comment]
> > > @arun-esh @ritikajaidka I have added the CI file on the assigned branch to this issue. PR #9 is the related PR.
> > > @ritikajaidka needs to setup the secret key. Also check @ritikajaidka 's email and APP name in YAML file.
> > 
> > 
> > Only Heroku account holder can generate API secret?
> 
> Anyone can with access I guess. Email should match the account of API secret key.

Another thing, repo owner has to add that API key into the REPO settings which we can't do.

**Comment by arun-esh** [comment]
@jalpa015 @ritikajaidka 
Is there anything I can be any help for this issue?

**Comment by jalpa015** [comment]
> @jalpa015 @ritikajaidka Is there anything I can be any help for this issue?

API Secret Key has been added. Waiting for the other PR I believe.
